name: Test feature branch
'on':
  push:
    branches:
      - '*'
      - '!main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: sudo ./setup_env.sh
      - uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: "http://localhost:3000"
          headless: true