name: Test feature branch
'on':
  push:
    branches:
      - '*'
      - '!main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup environment
      run:  |
        chmod +x ./setup_env.sh
        ./setup_env.sh
        less ./.env
      - name: End to end testing
      - uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: "http://localhost:3000"
          headless: true